/**
 * Backend
 * Descripción
 *
 * OpenAPI spec version: 0.0.1
 * Contact: willypanza11@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PostDto } from './postDto';

export interface GenericResponseListPostDto { 
    message?: string;
    object?: Array<PostDto>;
    status?: number;
}